config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete_vericication"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update-profile"),
    path(
        "update-password/", views.UpdatePasswordView.as_view(), name="update-password"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
]

templates/partials/authForm.html
<form method="POST" class="w-full" enctype="multipart/form-data">
    {% csrf_token %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <span class="text-red-700 font-medium text-xs">{{error}}</span>
        {% endfor %}
    {% endif %}

    {% for field in form %}
        <div class="input {% if field.errors %}has_error{% endif %}">
        <!-- {{field.label}} -->
        {{field}}
        {% if field.errors %}
            {% for error in field.errors %}
            <span class="text-red-700 font-medium text-xs">{{error}}<br></span>
            {% endfor %}
        {% endif %}
        </div>
    {% endfor %}

    <button class="btn bg-red-500 text-white my-2">{{Content}}</button>
</form>

templates/partials/footer.html
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500">
  &copy; 2020 Nbnb. Inc. All rights reserved.
</footer>

templates/partials/messages.html
{% if messages %}
    <ul class="message_ul fixed z-10 w-full mr-3 right-0 bottom-0 flex flex-col items-end">
        {% for message in messages %}
            <div class="message font-medium shadow-lg rounded-sm w-auto mb-1 py-3 px-6 text-center {% if message.tags %}{{message.tags}}{% endif %}">{{message}}</div>
        {% endfor %}  
    </ul>
{% endif %}
    

templates/partials/nav.html
<ul class="flex items-center text-sm font-medium h-full">
  {% if user.is_authenticated %}
  <li class="nav_link"><a href="{{user.get_absolute_url}}">Profile</a></li>
  <li class="nav_link"><a href="{% url 'users:logout' %}">Logout</a></li>
  {% else %}
  <li class="nav_link">
    <a href="{% url 'users:login' %}">Login</a>
  </li>
  <li class="nav_link">
    <a href="{% url 'users:signup' %}">Sign Up</a>
  </li>
  {% endif %}
</ul>

templates/partials/room_card.html
<div class="w-1/4 mb-10 px-2">
  <a href="{% url 'rooms:detail' room.pk %}">
    <div class="w-full h-64 rounded-lg bg-cover bg-center rounded-lg mb-2" style="background-image: url({{room.first_photo}});"></div>
  </a>
  <div class="flex justify-between mb-2">
    <div class="truncate">
      {% if room.host.superhost %}
      <span class="uppercase mr-px font-semibold text-xs border border-red-600 text-red-600 rounded px-1">superhost</span>
      {% endif %}
      <span class="text-sm text-gray-600 font-light">{{room.city}}, {{room.country.name}}</span>
    </div>
    <span class="text-sm flex items-center">
      <i class="fas fa-star text-red-500 text-xs mr-px"></i> {{room.tatal_rating}}
    </span>
  </div>
  <div class="text-black overflow-hidden">
    <a href="{% url 'rooms:detail' room.pk %}">
      <span class="text-black truncate block">{{room.name}}</span>
    </a>
  </div>
</div>

templates/partials/social_login.html
<div class="flex flex-col w-full">
  <a href="{% url 'users:github-login' %}" class="btn border-2 border-gray-600 text-gray-700">
    <i class="fab fa-github fa-lg mx-2"></i>
    <span>Continue with GitHub</span>
  </a>
  <a href="{% url 'users:kakao-login' %}" class="btn bg-yellow-400 border border-yellow-600 text-yellow-700">
    <i class="fas fa-comment fa-lg mx-2"></i>
    <span>Continue with Kakao</span>
  </a>
</div>

<div class="flex items-center w-full my-5">
  <div class="h-px w-full bg-gray-400"></div>
  <span class="text-gray-600 font-medium mx-2 text-sm">or</span>
  <div class="h-px w-full bg-gray-400"></div>
</div>

templates/partials/user_avatar.html
{% if user.avatar %}
    <div class="{{h_and_w|default:'h-20 w-20'}} bg-cover rounded-full" style="background-image: url({{user.avatar.url}});"></div>
{% else %}
    <div class="{{h_and_w|default:'h-20 w-20'}} overflow-hidden bg-gray-700 rounded-full text-white flex justify-center items-center">
        <span class="{{text|default:'text-3xl'}}">{{user.last_name|first}}</span>
    </div>
{% endif %}