config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete_vericication"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update-profile"),
    path(
        "update-password/", views.UpdatePasswordView.as_view(), name="update-password"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
]

users/models.py
import uuid
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.template.loader import render_to_string
from django.urls import reverse


class User(AbstractUser):

    """Custom User Model Definition"""

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_CHOICES = ((GENDER_MALE, "Male"), (GENDER_FEMALE, "Female"))

    LANG_KR = "kr"
    LANG_EN = "en"
    LANG_CHOICES = ((LANG_KR, "KOREAN"), (LANG_EN, "ENGLISH"))

    CURRNECY_KRW = "krw"
    CURRENCY_USD = "usd"
    CURRENCY_CHOICES = ((CURRNECY_KRW, "KRW"), (CURRENCY_USD, "USD"))

    LOGIN_EMAIL = "email"
    LOGIN_GITHUB = "github"
    LOGIN_KAKAO = "kakao"
    LOGIN_CHOICES = (
        (LOGIN_EMAIL, "Email"),
        (LOGIN_GITHUB, "Github"),
        (LOGIN_KAKAO, "Kakao"),
    )

    avatar = models.ImageField(upload_to="avatars", blank=True)
    nickname = models.CharField(max_length=20, blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=10, blank=True)
    bio = models.TextField(default="", blank=True)
    birthdate = models.DateField(null=True, blank=True)
    language = models.CharField(
        choices=LANG_CHOICES, max_length=2, blank=True, default=LANG_KR
    )
    currency = models.CharField(
        choices=CURRENCY_CHOICES, max_length=3, blank=True, default=CURRNECY_KRW
    )
    superhost = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)
    email_authKey = models.CharField(max_length=20, default="", blank=True)
    login_method = models.CharField(
        choices=LOGIN_CHOICES, max_length=50, default=LOGIN_EMAIL
    )

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

    def verify_email(self):
        if self.email_verified is False:
            key = uuid.uuid4().hex[:20]
            self.email_authKey = key
            html_message = render_to_string("emails/verify_email.html", {"key": key})
            send_mail(
                subject="Verify Airbnb Account",
                message=strip_tags(html_message),
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[self.email],
                fail_silently=True,
                html_message=html_message,
            )
            self.save()
        return

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


class SignUpForm(UserCreationForm):
    class Meta:
        model = models.User
        fields = (
            "first_name",
            "last_name",
            "email",
        )
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email"}),
        }

    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"})
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError("That email is already taken")
        except models.User.DoesNotExist:
            return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.username = self.cleaned_data.get("email")
        if commit:
            user.save()
        return user

users/views.py
import os
import requests
from django.http import QueryDict
from django.views.generic import FormView, DetailView, UpdateView
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LogoutView, PasswordChangeView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.files.base import ContentFile
from . import forms, models, mixins


class LoginView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            messages.add_message(self.request, messages.SUCCESS, "Login Success!")
            return reverse("core:home")


class LogoutView(LogoutView):
    def get_next_page(self):
        next_page = reverse_lazy("core:home")
        messages.success(self.request, "See you later!")
        return next_page


class SignUpView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    # Auto Login
    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
            messages.success(self.request, "SignUp Success!")
            messages.success(self.request, "Thank you to with us!")
        user.verify_email()  # send email
        return super().form_valid(form)


# Email Verification
def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_authKey=key)
        user.email_verified = True
        user.email_authKey = ""
        user.save()
        # to do: add success message
    except models.User.DoesNotExist:
        # to do: add error message
        pass
    return redirect(reverse("core:home"))


def github_login(request):
    q = QueryDict(mutable=True)
    q["client_id"] = os.environ.get("GITHUB_ID")
    q["redirect_uri"] = "http://127.0.0.1:8000/users/login/github/callback"
    q["scope"] = "read:user"
    query_string = q.urlencode()
    return redirect("https://github.com/login/oauth/authorize?" + query_string)


class GithubException(Exception):
    pass


def github_callback(request):
    try:
        code = request.GET.get("code", None)
        q = QueryDict(mutable=True)
        q["client_id"] = os.environ.get("GITHUB_ID")
        q["client_secret"] = os.environ.get("GITHUB_SECRET")
        q["code"] = code
        query_string = q.urlencode()
        if code is not None:
            result = requests.post(
                "https://github.com/login/oauth/access_token?" + query_string,
                headers={"Accept": "application/json"},
            )
            result_json = result.json()
            error = result_json.get("error", None)
            if error is not None:
                raise GithubException("Login Fail")
            else:
                access_token = result_json.get("access_token")
                profile_request = requests.get(
                    "https://api.github.com/user",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                profile_json = profile_request.json()
                username = profile_json.get("login", None)
                if username is not None:
                    name = profile_json.get("name")
                    if name is None:
                        name = "None"
                    email = profile_json.get("email")
                    if email is None:
                        email = "None"
                    bio = profile_json.get("bio")
                    if bio is None:
                        bio = "None"
                    try:
                        user = models.User.objects.get(email=email)
                        if user.login_method != models.User.LOGIN_GITHUB:
                            raise GithubException(
                                f'Login Fail. Please Login with "{user.login_method}"'
                            )
                    except models.User.DoesNotExist:
                        user = models.User.objects.create(
                            username=email,
                            first_name=name,
                            bio=bio,
                            email=email,
                            login_method=models.User.LOGIN_GITHUB,
                        )
                        if email != "None":
                            user.email_verified = True
                        user.set_unusable_password()
                        user.save()
                    login(request, user)
                    messages.success(request, "Login Success!")
                    return redirect(reverse("core:home"))
                else:
                    raise GithubException("Login Fail")
        else:
            raise GithubException("Login Fail")
    except GithubException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


def kakao_login(request):
    q = QueryDict(mutable=True)
    q["client_id"] = os.environ.get("KAKAO_ID")
    q["redirect_uri"] = "http://127.0.0.1:8000/users/login/kakao/callback"
    q["response_type"] = "code"
    query_string = q.urlencode()
    return redirect("https://kauth.kakao.com/oauth/authorize?" + query_string)


class Kakao_Exception(Exception):
    pass


def kakao_callback(request):
    try:
        code = request.GET.get("code", None)
        q = QueryDict(mutable=True)
        q["grant_type"] = "authorization_code"
        q["client_id"] = os.environ.get("KAKAO_ID")
        q["redirect_uri"] = "http://127.0.0.1:8000/users/login/kakao/callback"
        q["code"] = code
        query_string = q.urlencode()
        if code is not None:
            token_request = requests.post(
                "https://kauth.kakao.com/oauth/token?" + query_string
            )
            token_json = token_request.json()
            error = token_json.get("error", None)
            if error is not None:
                raise Kakao_Exception("Login Fail.")
            access_token = token_json.get("access_token")
            profile_request = requests.get(
                "https://kapi.kakao.com/v2/user/me",
                headers={"Authorization": f"Bearer {access_token}"},
            )
            profile_json = profile_request.json()
            email = profile_json.get("kakao_account").get("email", None)
            if email is None:
                raise Kakao_Exception("Login Fail.", "Please agree for use email")
            nickname = (
                profile_json.get("kakao_account").get("profile").get("nickname", None)
            )
            profile_image = (
                profile_json.get("kakao_account")
                .get("profile")
                .get("profile_image_url", None)
            )
            try:
                user = models.User.objects.get(email=email)
                if user.login_method != models.User.LOGIN_KAKAO:
                    raise Kakao_Exception(
                        "Login Fail.", f'Please Login with "{user.login_method}"',
                    )
            except models.User.DoesNotExist:
                user = models.User.objects.create(
                    username=email,
                    email=email,
                    first_name=nickname,
                    login_method=models.User.LOGIN_KAKAO,
                    email_verified=True,
                )
                user.set_unusable_password()
                user.save()
                if profile_image is not None:
                    photo_request = requests.get(profile_image)
                    user.avatar.save(
                        f"{nickname}-avatar", ContentFile(photo_request.content)
                    )
                    print("avatar" * 20, profile_image)
            login(request, user)
            messages.success(request, "Login Success!")
            return redirect(reverse("core:home"))
    except Kakao_Exception as e:
        for i in e.args:
            messages.error(request, i)
        return redirect(reverse("users:login"))


class UserProfileView(DetailView):

    model = models.User
    context_object_name = "user_obj"


class UpdateProfileView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "first_name",
        "last_name",
        "nickname",
        "avatar",
        "gender",
        "bio",
        "birthdate",
        "language",
        "currency",
    )
    success_message = "Profile updated successfully"

    def get_object(self, queryset=None):
        return self.request.user

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["first_name"].widget.attrs = {"placeholder": "First Name"}
        form.fields["last_name"].widget.attrs = {"placeholder": "Last Name"}
        form.fields["nickname"].widget.attrs = {"placeholder": "Nickname"}
        form.fields["bio"].widget.attrs = {"placeholder": "Introduce yourself"}
        form.fields["birthdate"].widget.attrs = {"placeholder": "0000-00-00 (BirthDay)"}

templates/users/login.html
{% extends "base.html" %}

{% block page_name %}
  Login
{% endblock page_name %} 

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
  <div class="container lg:w-1/3 md:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    
    {% include "partials/social_login.html" %}
    {% include 'partials/authForm.html' with form=form Content="Login" %}
    
    <div class="flex justify-between items-center w-full">
      <span class="text-sm text-gray-600">Don't have an account?</span>
      <a href="{% url 'users:signup' %}" class="text-sm text-teal-500 border border-white rounded-sm px-3 py-1 font-semibold hover:border-teal-500">Sign up</a>
    </div>

  </div>
{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}

{% block page_name %}
  Sign up
{% endblock page_name %} 

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
  <div class="container lg:w-1/3 md:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    
    {% include "partials/social_login.html" %}
    {% include 'partials/authForm.html' with form=form Content="Sign Up" %}

    <div class="flex justify-between items-center w-full">
      <span class="text-sm text-gray-600">Have an account?</span>
      <a href="{% url 'users:login' %}" class="text-sm text-teal-500 border border-white rounded-sm px-3 py-1 font-semibold hover:border-teal-500">Login</a>
    </div>

  </div>
{% endblock content %}

templates/users/update-password.html
{% extends "base.html" %}

{% block page_name %}
    Update Password
{% endblock page_name %} 

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="min-h-75vh">
        <div class="container lg:w-1/3 md:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">        
            {% include 'partials/authForm.html' with form=form Content="Update Password" %}
        </div>
    </div>
{% endblock content %}

templates/users/update-profile.html
{% extends "base.html" %}

{% block page_name %}
  Update Profile
{% endblock page_name %} 

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
  <div class="container lg:w-1/3 md:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    
    {% include 'partials/authForm.html' with form=form Content="Update Profile" %}
    
    {% if object.login_method == "email" %}
      <div class="flex justify-center items-center w-full">
        <a href="{% url 'users:update-password' %}" class="text-sm text-teal-500 border-b border-white rounded-sm px-3 py-1 font-semibold hover:border-teal-500">Change Password</a>
      </div>
    {% endif %}
      

  </div>
{% endblock content %}

templates/users/user_detail.html
{% extends "base.html" %}

{% block page_name %}
  Profile
{% endblock page_name %} 

{% block content %}
  <div class="min-h-75vh">

    <!-- Profile Card -->
    <div class="container lg:w-1/3 md:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
      
      {% include 'partials/user_avatar.html' with user=user_obj %}
      
      {% if user_obj.nickname %}
        <span class="text-2xl mt-1 my-1">{{user_obj.nickname}}</span>
      {% else %} 
        <span class="text-2xl mt-1 my-1">{{user_obj.last_name}}</span>
      {% endif %}
        
      {% if user_obj.superhost %}
        <span class="text-xs font-semibold border border-red-600 text-red-600 rounded-md px-1 my-1">SUPERHOST</span>
      {% endif %}
      <div class="h-px w-full border-t my-3"></div>
      <span class="text-lg">{{user_obj.bio}}</span>
  
      {% if user == user_obj %}
          <a href="{% url 'users:update-profile' %}" class="btn bg-red-500 text-white">Edit Profile</a>      
      {% endif %}
  
    </div>
  
    <!-- Rooms List -->
    <div class="container mx-auto flex flex-col items-center">
      {% if user_obj.rooms.count > 0 %}
        <div class="h-px w-full border-t my-3"></div>
        {% if user_obj.nickname %}
          <h3 class="text-center font-bold text-lg my-2">{{user_obj.nickname}}'s Rooms</h3>
        {% else %} 
          <h3 class="text-center font-bold text-lg my-2">{{user_obj.last_name}}'s Rooms</h3>
        {% endif %}
        <div class="h-px w-full border-t my-3"></div>
        <div class="flex flex-wrap my-5 justify-center w-full">
          {% for room in user_obj.rooms.all %}
            {% include 'partials/room_card.html' with room=room %}
          {% endfor %}
        </div>
      {% endif %}
    </div>

  </div>

{% endblock content %}